# Generated by Django 5.2.4 on 2025-07-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
